server:
  # 服务地圵
  address: ":8955"
  # 读超时时间
  readtimeout: "10s"
  # 写超时时间
  writetimeout: "10s"

log:
  # 日志级别, 支持 debug info warn error panic fatal ，默认info
  level: debug
  # 是否输出到终端，仅在开发环境有效
  stdout: false